---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-config
  namespace: bggns
data:
  bgg_db_user: root
  bgg_db_host: bggdb-svc.bggns.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
  namespace: bggns
data:
  bgg_db_password: Y2hhbmdlaXQ=