apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-database-deploy
  namespace: bggns
  labels:
    app: bgg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
  template:
    metadata:
      name: bggdb-po
      labels:
        app: bgg
        name: bggdb-po
    spec:
      containers:
      - name: bgg-database-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: db-port
          containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
spec:
  type: ClusterIP  # Ensures the service is only accessible within the cluster
  selector:
    app: bgg
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: 3306
